status = [
    "Audit",
    "Code lint",
    "Test on linux",
    "Test on linux-aarch64",
    "Test on macos",
    "Test on windows",
    "Test cross-compile on linux",
    "Test cross-compile on macos",
]
required_approvals = 1
timeout_sec = 7200
delete_merged_branches = true 
