name: test-sys

on:
  push:
    branches:
      - '**'
      - '!master'
    pull_request:
        types: [ synchronize ]
  workflow_dispatch:
    inputs:
      release:
          description: 'Make release'
env:
  RUST_BACKTRACE: 1

jobs:

  setup:
    name: Set up
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.setup.outputs.VERSION }}
      DOING_RELEASE: ${{ steps.setup.outputs.DOING_RELEASE }}
    steps:
      - name: Set up env vars
        id: setup
        shell: bash
        run: |
          VERSION=${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=VERSION::${VERSION}
          DOING_RELEASE=$(echo $VERSION | grep -c '^[0-9]\+\.[0-9]\+\.[0-9]\+\(-\([a-zA-Z]\+\)\?[0-9]*\)\?$' || true)
          echo ::set-output name=DOING_RELEASE::${DOING_RELEASE}
          echo $VERSION
          echo $DOING_RELEASE

  lint:
    name: Code lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.63
          components: rustfmt, clippy
      - name: Install LLVM (Linux)
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz -L -o /opt/llvm.tar.xz
          mkdir -p /opt/llvm-12
          tar xf /opt/llvm.tar.xz --strip-components=1 -C /opt/llvm-12
          echo '/opt/llvm-12/bin' >> $GITHUB_PATH
          echo 'LLVM_SYS_120_PREFIX=/opt/llvm-12' >> $GITHUB_ENV
      - run: make lint
        env:
          ENABLE_CRANELIFT: "1"
          ENABLE_LLVM: "1"
          ENABLE_SINGLEPASS: "1"
      - name: Assert no files have changed
        run: |
          git status
          ! [[ $(git status -s) ]]

  cargo_deny:
    name: cargo-deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1

  test_nodejs:
    name: Test on NodeJS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.63
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: make test-js
        run: |
          make test-js
      - name: make test-js-core
        run: |
          make test-js-core

  test_wasm_build:
    name: Test wasm build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          rustup target add wasm32-wasi
          make build-wasmer-wasm

  # build-wasmer: run build-wasmer and build-capi for every OS in parallel
  build_wasmer: 
    name: Build wasmer on ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: linux-x64
            os: ubuntu-18.04
            target: x86_64-unknown-linux-gnu
            llvm_url: 'https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz'
            run_test: true
            run_test_capi: true
            run_integration_tests: true
            run_build_docs: true
            use_sccache: true
          - build: macos-x64
            os: macos-11
            target: x86_64-apple-darwin
            llvm_url: 'https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/clang+llvm-13.0.0-x86_64-apple-darwin.tar.xz'
            run_test: true
            run_test_capi: true
            use_sccache: true
            run_integration_tests: true
            run_ios_tests: true
            run_build_docs: false
          - build: macos-arm64
            os: macos-11.0
            target: aarch64-apple-darwin
            use_sccache: true
            run_test: false
            run_test_capi: false
            run_build_docs: false
          - build: windows-x64
            os: windows-2019
            #target: x86_64-pc-windows-msvc commented because of bug in rust setup action
            # llvm_url: 'https://github.com/wasmerio/llvm-custom-builds/releases/download/12.x/windows-amd64.tar.gz'
            llvm_choco_version: 13.0.0
            run_integration_tests: true
            use_sccache: true
            run_test: true
            run_test_capi: false # We can't run yet the capi tests on Windows
            run_build_docs: false
          - build: linux-musl-x64
            target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            container: alpine:latest
            run_test: true
            run_test_capi: false # It can't run the capi tests because of a cc linker issue (`wasm_engine_new` is redefined)
            run_integration_tests: false
            run_build_docs: false
            use_sccache: false
    container: ${{ matrix.container }}
    env:
      SCCACHE_AZURE_BLOB_CONTAINER: wasmerstoragesccacheblob
      SCCACHE_AZURE_CONNECTION_STRING: ${{ secrets.SCCACHE_AZURE_CONNECTION_STRING }}
    steps:
      - uses: actions/checkout@v3

  build_capi: 
    name: Build C-API on ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: linux-x64
            os: ubuntu-18.04
            target: x86_64-unknown-linux-gnu
            llvm_url: 'https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz'
            run_test: true
            run_test_capi: true
            run_integration_tests: true
            run_build_docs: true
            use_sccache: true
          - build: macos-x64
            os: macos-11
            target: x86_64-apple-darwin
            llvm_url: 'https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/clang+llvm-13.0.0-x86_64-apple-darwin.tar.xz'
            run_test: true
            run_test_capi: true
            use_sccache: true
            run_integration_tests: true
            run_ios_tests: true
            run_build_docs: false
          - build: macos-arm64
            os: macos-11.0
            target: aarch64-apple-darwin
            use_sccache: true
            run_test: false
            run_test_capi: false
            run_build_docs: false
          - build: windows-x64
            os: windows-2019
            #target: x86_64-pc-windows-msvc commented because of bug in rust setup action
            # llvm_url: 'https://github.com/wasmerio/llvm-custom-builds/releases/download/12.x/windows-amd64.tar.gz'
            llvm_choco_version: 13.0.0
            run_integration_tests: true
            use_sccache: true
            run_test: true
            run_test_capi: false # We can't run yet the capi tests on Windows
            run_build_docs: false
          - build: linux-musl-x64
            target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            container: alpine:latest
            run_test: true
            run_test_capi: false # It can't run the capi tests because of a cc linker issue (`wasm_engine_new` is redefined)
            run_integration_tests: false
            run_build_docs: false
            use_sccache: false
    container: ${{ matrix.container }}
    env:
      SCCACHE_AZURE_BLOB_CONTAINER: wasmerstoragesccacheblob
      SCCACHE_AZURE_CONNECTION_STRING: ${{ secrets.SCCACHE_AZURE_CONNECTION_STRING }}
    steps:
      - uses: actions/checkout@v3

  test_wasmer: 
    name: Test Wasmer on ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: linux-x64
            os: ubuntu-18.04
            target: x86_64-unknown-linux-gnu
            llvm_url: 'https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz'
            run_test: true
            run_test_capi: true
            run_integration_tests: true
            run_build_docs: true
            use_sccache: true
          - build: macos-x64
            os: macos-11
            target: x86_64-apple-darwin
            llvm_url: 'https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/clang+llvm-13.0.0-x86_64-apple-darwin.tar.xz'
            run_test: true
            run_test_capi: true
            use_sccache: true
            run_integration_tests: true
            run_ios_tests: true
            run_build_docs: false
          - build: macos-arm64
            os: macos-11.0
            target: aarch64-apple-darwin
            use_sccache: true
            run_test: false
            run_test_capi: false
            run_build_docs: false
          - build: windows-x64
            os: windows-2019
            #target: x86_64-pc-windows-msvc commented because of bug in rust setup action
            # llvm_url: 'https://github.com/wasmerio/llvm-custom-builds/releases/download/12.x/windows-amd64.tar.gz'
            llvm_choco_version: 13.0.0
            run_integration_tests: true
            use_sccache: true
            run_test: true
            run_test_capi: false # We can't run yet the capi tests on Windows
            run_build_docs: false
          - build: linux-musl-x64
            target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            container: alpine:latest
            run_test: true
            run_test_capi: false # It can't run the capi tests because of a cc linker issue (`wasm_engine_new` is redefined)
            run_integration_tests: false
            run_build_docs: false
            use_sccache: false
    container: ${{ matrix.container }}
    env:
      SCCACHE_AZURE_BLOB_CONTAINER: wasmerstoragesccacheblob
      SCCACHE_AZURE_CONNECTION_STRING: ${{ secrets.SCCACHE_AZURE_CONNECTION_STRING }}
    steps:
      - uses: actions/checkout@v3

  test_capi: 
    name: Test C-API on ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    needs: build_capi
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: linux-x64
            os: ubuntu-18.04
            target: x86_64-unknown-linux-gnu
            llvm_url: 'https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz'
            run_test: true
            run_test_capi: true
            run_integration_tests: true
            run_build_docs: true
            use_sccache: true
          - build: macos-x64
            os: macos-11
            target: x86_64-apple-darwin
            llvm_url: 'https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/clang+llvm-13.0.0-x86_64-apple-darwin.tar.xz'
            run_test: true
            run_test_capi: true
            use_sccache: true
            run_integration_tests: true
            run_ios_tests: true
            run_build_docs: false
          - build: macos-arm64
            os: macos-11.0
            target: aarch64-apple-darwin
            use_sccache: true
            run_test: false
            run_test_capi: false
            run_build_docs: false
          - build: windows-x64
            os: windows-2019
            #target: x86_64-pc-windows-msvc commented because of bug in rust setup action
            # llvm_url: 'https://github.com/wasmerio/llvm-custom-builds/releases/download/12.x/windows-amd64.tar.gz'
            llvm_choco_version: 13.0.0
            run_integration_tests: true
            use_sccache: true
            run_test: true
            run_test_capi: false # We can't run yet the capi tests on Windows
            run_build_docs: false
          - build: linux-musl-x64
            target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            container: alpine:latest
            run_test: true
            run_test_capi: false # It can't run the capi tests because of a cc linker issue (`wasm_engine_new` is redefined)
            run_integration_tests: false
            run_build_docs: false
            use_sccache: false
    container: ${{ matrix.container }}
    env:
      SCCACHE_AZURE_BLOB_CONTAINER: wasmerstoragesccacheblob
      SCCACHE_AZURE_CONNECTION_STRING: ${{ secrets.SCCACHE_AZURE_CONNECTION_STRING }}
    steps:
      - uses: actions/checkout@v3

  test_integration_cli: 
    name: Integration tests on ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    needs: [build_capi, build_wasmer]
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: linux-x64
            os: ubuntu-18.04
            target: x86_64-unknown-linux-gnu
            llvm_url: 'https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz'
            run_test: true
            run_test_capi: true
            run_integration_tests: true
            run_build_docs: true
            use_sccache: true
          - build: macos-x64
            os: macos-11
            target: x86_64-apple-darwin
            llvm_url: 'https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/clang+llvm-13.0.0-x86_64-apple-darwin.tar.xz'
            run_test: true
            run_test_capi: true
            use_sccache: true
            run_integration_tests: true
            run_ios_tests: true
            run_build_docs: false
          - build: macos-arm64
            os: macos-11.0
            target: aarch64-apple-darwin
            use_sccache: true
            run_test: false
            run_test_capi: false
            run_build_docs: false
          - build: windows-x64
            os: windows-2019
            #target: x86_64-pc-windows-msvc commented because of bug in rust setup action
            # llvm_url: 'https://github.com/wasmerio/llvm-custom-builds/releases/download/12.x/windows-amd64.tar.gz'
            llvm_choco_version: 13.0.0
            run_integration_tests: true
            use_sccache: true
            run_test: true
            run_test_capi: false # We can't run yet the capi tests on Windows
            run_build_docs: false
          - build: linux-musl-x64
            target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            container: alpine:latest
            run_test: true
            run_test_capi: false # It can't run the capi tests because of a cc linker issue (`wasm_engine_new` is redefined)
            run_integration_tests: false
            run_build_docs: false
            use_sccache: false
    container: ${{ matrix.container }}
    env:
      SCCACHE_AZURE_BLOB_CONTAINER: wasmerstoragesccacheblob
      SCCACHE_AZURE_CONNECTION_STRING: ${{ secrets.SCCACHE_AZURE_CONNECTION_STRING }}
    steps:
      - uses: actions/checkout@v3

  # todo: build wasmer headless

  # build-capi: run build-capi for every OS, does NOT depend on build-wasmer
  # (can run in parallel with build-wasmer step)

  # make test: run unit tests for wasmer, depends on build-wasmer step
  # (can run in parallel with build-capi step)

  # test-integration-cli: run integration tests for wasmer, depends on build-capi and build-wasmer steps
