name: test-sys

on:
  push:
    branches:
      - '**'
      - '!master'
    pull_request:
        types: [ synchronize ]

env:
  RUST_BACKTRACE: 1

jobs:

  check_linux_x64:
    name: cargo check on linux-x86_64-gnu
    runs-on: ubuntu-18.04
    env:
      TARGET: linux-x86_64-gnu
    steps: 
      - uses: actions/checkout@v3
      - name: Set up libstdc++ on Linux
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --allow-downgrades libstdc++6=8.4.0-1ubuntu1~18.04
          sudo apt-get install --reinstall g++-8
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.63
          target: x86_64-unknown-linux-gnu
      - name: Install cargo xtask
        run: |
          cargo install cargo-xtask
      - name: cargo xtask build-wasmer
        run: |
          cargo xtaskci

  check_linux_musl:
    name: cargo check on linux-x86_64-musl
    runs-on: ubuntu-latest
    container: alpine:latest
>>>>>>> 3e578e17a5 (Remove unnecessary CI runs)
    env:
      TARGET: linux-x86_64-musl
    steps: 
      - uses: actions/checkout@v3
      - name: Set up base deps on musl
        run: |
            apk add build-base bash musl-dev curl make libtool libffi-dev gcc automake autoconf git openssl-dev g++
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.63
          target: x86_64-unknown-linux-musl
      - name: Install cargo xtask
        run: |
          cargo install cargo-xtask
      - name: cargo xtask build-wasmer
        run: |
          cargo xtaskci

  check_windows:
    name: cargo check on windows-x64
    runs-on: windows-2019
    env:
      TARGET: windows-x86_64-msvc
    steps: 
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.63
          target: x86_64-unknown-linux-musl
      - name: Install cargo xtask
        run: |
          cargo install cargo-xtask
      - name: cargo xtask build-wasmer
        run: |
          cargo xtaskci